version: "3.7"
services:
  rabbitmq-web-4:
    image: rabbitmq-web-4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
